apiVersion: 1
contactPoints:
  - orgId: 1
    name: TestEmail
    receivers:
      - uid: testemail-receiver
        type: email
        disableResolveMessage: false
        settings:
          addresses: test@localhost
          singleEmail: false
          subject: |
            {{ template "default.title" . }}
          message: |
            {{ template "default.message" . }}
