admin:
  existingSecret: grafana-secret
  userKey: user
  passwordKey: password

service:
  type: NodePort
  port: 3000
  nodePort: 32000

persistence:
  enabled: true
  size: 2Gi

grafana.ini:
  smtp:
    enabled: true
    host: smtp4dev.monitoring.svc.cluster.local:25
    from_address: test@localhost
    from_name: Grafana Alerts
    skip_verify: true

smtp:
  enabled: true
  host: smtp4dev.monitoring.svc.cluster.local:25
  skipVerify: true
  from_address: test@localhost
  from_name: Grafana Alerts

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        url: http://kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
        access: proxy
        isDefault: true

extraVolumes:
  - name: contact-points
    configMap:
      name: contact-points
  - name: grafana-policies
    configMap:
      name: grafana-policies
  - name: grafana-rules
    configMap:
      name: grafana-rules

extraVolumeMounts:
  - name: contact-points
    mountPath: /opt/bitnami/grafana/conf/provisioning/alerting/contact-points.yaml
    subPath: contact-points.yaml
    readOnly: true
  - name: grafana-policies
    mountPath: /opt/bitnami/grafana/conf/provisioning/alerting/notification-policies.yaml
    subPath: notification-policies.yaml
    readOnly: true
  - name: grafana-rules
    mountPath: /opt/bitnami/grafana/conf/provisioning/rules/rule-groups.yaml
    subPath: rule-groups.yaml
    readOnly: true
