controller:
  persistence:
    enabled: true
    size: 4Gi
  JCasC:
    enabled: false
#    configScripts:
#      hello-job: |
#        jobs:
#          - script: >
#              pipelineJob('hello-world-pipeline') {
#                definition {
#                  cps {
#                    script(\"\"\"
#                      pipeline {
#                        agent any
#                        stages {
#                          stage('Hello') {
#                            steps {
#                              echo 'Hello world'
#                            }
#                          }
#                        }
#                      }
#                    \"\"\")
#                  }
#                }
#              }
