controller:
  persistence:
    enabled: true
    size: 4Gi

#  JCasC:
#    enabled: true
#    configScripts:
#      prometheus-job: |
#        jobs:
#          - script: >
#              pipelineJob('task-7-prometheus') {
#                definition {
#                  cpsScm {
#                    scm {
#                      git {
#                        remote {
#                          url('https://github.com/IharTsykala/rsschool-devops-course-tasks-2025q2.git')
#                        }
#                        branches('*/feat/task-7-prometheus-deployment-on-k8s')
#                      }
#                    }
#                    scriptPath('kubernetes/prometheus/Jenkinsfile')
#                  }
#                }
#              }
